/*
 * @(#) PartList.cpp   1.0   Nov 5, 2013
 *
 * Andrea Maesani (andrea.maesani@epfl.ch)
 *
 * The ROBOGEN Framework
 * Copyright © 2012-2013 Andrea Maesani
 *
 * Laboratory of Intelligent Systems, EPFL
 *
 * This file is part of the ROBOGEN Framework.
 *
 * The ROBOGEN Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPL)
 * as published by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @(#) $Id$
 */
#include "PartList.h"

PART_TYPE_MAP['K'] = PART_TYPE_ACTIVE_CARDAN;
PART_TYPE_MAP['I'] = PART_TYPE_ACTIVE_HINGE;
PART_TYPE_MAP['J'] = PART_TYPE_ACTIVE_WHEEL;
PART_TYPE_MAP['G'] = PART_TYPE_ACTIVE_WHEG;
PART_TYPE_MAP['E'] = PART_TYPE_CORE_COMPONENT;
PART_TYPE_MAP['F'] = PART_TYPE_FIXED_BRICK;
PART_TYPE_MAP['L'] = PART_TYPE_LIGHT_SENSOR;
PART_TYPE_MAP['B'] = PART_TYPE_PARAM_JOINT;
PART_TYPE_MAP['C'] = PART_TYPE_PASSIVE_CARDAN;
PART_TYPE_MAP['H'] = PART_TYPE_PASSIVE_HINGE;
PART_TYPE_MAP['W'] = PART_TYPE_PASSIVE_WHEEL;
PART_TYPE_MAP['R'] = PART_TYPE_ROTATOR;
PART_TYPE_MAP['T'] = PART_TYPE_TOUCH_SENSOR;

PART_TYPE_ARITY_MAP[PART_TYPE_ACTIVE_CARDAN] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_ACTIVE_HINGE] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_ACTIVE_WHEEL] = 0;
PART_TYPE_ARITY_MAP[PART_TYPE_ACTIVE_WHEG] = 0;
PART_TYPE_ARITY_MAP[PART_TYPE_CORE_COMPONENT] = 5;
PART_TYPE_ARITY_MAP[PART_TYPE_FIXED_BRICK] = 5;
PART_TYPE_ARITY_MAP[PART_TYPE_LIGHT_SENSOR] = 0;
PART_TYPE_ARITY_MAP[PART_TYPE_PARAM_JOINT] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_PASSIVE_CARDAN] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_PASSIVE_HINGE] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_PASSIVE_WHEEL] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_ROTATOR] = 1;
PART_TYPE_ARITY_MAP[PART_TYPE_TOUCH_SENSOR] = 0;

PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_ACTIVE_CARDAN] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_ACTIVE_HINGE] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_ACTIVE_WHEEL] = 1;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_ACTIVE_WHEG] = 1;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_CORE_COMPONENT] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_FIXED_BRICK] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_LIGHT_SENSOR] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_PARAM_JOINT] = 3;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_PASSIVE_CARDAN] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_PASSIVE_HINGE] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_PASSIVE_WHEEL] = 1;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_ROTATOR] = 0;
PART_TYPE_PARAM_COUNT_MAP[PART_TYPE_TOUCH_SENSOR] = 0;

// TODO Add motors and sensors map
PART_TYPE_MOTORS_MAP;

PART_TYPE_SENSORS_MAP;


